services:
  timescaledb:
    image: timescale/timescaledb:latest-pg18
    container_name: timescaledb
    restart: always
    environment:
      - POSTGRES_USER=${TIMESCALEDB_USER}
      - POSTGRES_PASSWORD=${TIMESCALEDB_PASSWORD}
      - POSTGRES_DB=${TIMESCALEDB_DB}
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - nenjo-network
  cache:
    image: redis:8.4.1-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

volumes:
  timescaledb_data:
  cache:
    driver: local

networks:
  nenjo-network:
    driver: bridge